# Path to output folder. 
# May be relative to this one.
# All output files will be stored here
folderOut:   ../out

# Gnuplot template
# Path to jinja2 templates, which will create a heat map from the weights.
pathTemplate: ../templates

# Dataset to load
# Path to MNIST dataset. Must contain mnist_test.csv and mnist_train.csv.
# Download from e.g.:
# https://www.python-course.eu/data/mnist/mnist_train.csv
# https://www.python-course.eu/data/mnist/mnist_test.csv
#pathDataset: ../data/random
pathDataset: ../data/correlated1
#pathDataset: ../data/correlated2
#pathDataset: ../data/mnist

# Scaling of input data
#scaling: rows
scaling: columns
#scaling: table
