# Path to output folder. 
# May be relative to this one.
# All output files will be stored here
folderOut:   ../out

# Gnuplot template
# Path to jinja2 templates, which will create a heat map from the weights.
pathTemplate: ../templates

# Dataset to load
# If folder, than dataset with files of filename YYYY-mm-dd_dataset-name_nr-x.nnv is expected. x has no leading 0.
# If filename, full path to file is expected (might be relative).
# If only name of dataset, i.e. random, correlated1, correlated2, samples are created.
# If path to MNIST dataset, the folder must contain mnist_test.csv and mnist_train.csv.
# Download from e.g.:
# https://www.python-course.eu/data/mnist/mnist_train.csv
# https://www.python-course.eu/data/mnist/mnist_test.csv
#pathDataset: ../data/random
pathDataset: ../data/correlated1
#pathDataset: ../data/correlated2
#pathDataset: ../data/mnist

# Scaling of input data
#scaling: rows
scaling: columns
#scaling: table
