# Path to output folder. 
# May be relative to this one.
# All output files will be stored here
folderOut: ../out

# Model to load
pathModel: ../out/2020-02-17_13-15-04_dataset-correlated2_nrruns-100_net.p
